# Generated by Django 4.2.6 on 2023-10-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': {('can_hide_comment', 'can hide comment')}},
        ),
    ]
