# Generated by Django 4.2.6 on 2023-10-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalprofile_historicalpost_historicalcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalComment',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
    ]
