# Generated by Django 4.2.6 on 2023-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_historicalpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
    ]
